version: 2

sources:
  - name: raw_data
    description: 'Raw Data for NYC taxi rides'
    database: kestra-project-486201
    schema: nytaxi
    tables: 
      - name: yellow_tripdata
      - name: green_tripdata